START TRANSACTION;
INSERT INTO `counties` (`id`, `name`, `number`) VALUES (1, 'Zagrebačka', 'I');
INSERT INTO `counties` (`id`, `name`, `number`) VALUES (2, 'Krapinsko-zagorska', 'II');
INSERT INTO `counties` (`id`, `name`, `number`) VALUES (3, 'Sisačko-moslavačka', 'III');
INSERT INTO `counties` (`id`, `name`, `number`) VALUES (4, 'Karlovačka', 'IV');
INSERT INTO `counties` (`id`, `name`, `number`) VALUES (9, 'Ličko-senjska', 'IX');
INSERT INTO `counties` (`id`, `name`, `number`) VALUES (5, 'Varaždinska', 'V');
INSERT INTO `counties` (`id`, `name`, `number`) VALUES (6, 'Koprivničko-križevačka', 'VI');
INSERT INTO `counties` (`id`, `name`, `number`) VALUES (7, 'Bjelovarsko-bilogorska', 'VII');
INSERT INTO `counties` (`id`, `name`, `number`) VALUES (8, 'Primorsko-goranska', 'VIII');
INSERT INTO `counties` (`id`, `name`, `number`) VALUES (10, 'Virovitičko-podravska', 'X');
INSERT INTO `counties` (`id`, `name`, `number`) VALUES (11, 'Požeško-slavonska', 'XI');
INSERT INTO `counties` (`id`, `name`, `number`) VALUES (12, 'Brodsko-posavska', 'XII');
INSERT INTO `counties` (`id`, `name`, `number`) VALUES (13, 'Zadarska', 'XIII');
INSERT INTO `counties` (`id`, `name`, `number`) VALUES (14, 'Osječko-baranjska', 'XIV');
INSERT INTO `counties` (`id`, `name`, `number`) VALUES (19, 'Dubrovačko-neretvanska', 'XIX');
INSERT INTO `counties` (`id`, `name`, `number`) VALUES (15, 'Šibensko-kninska', 'XV');
INSERT INTO `counties` (`id`, `name`, `number`) VALUES (16, 'Vukovarsko-srijemska', 'XVI');
INSERT INTO `counties` (`id`, `name`, `number`) VALUES (17, 'Splitsko-dalmatinska', 'XVII');
INSERT INTO `counties` (`id`, `name`, `number`) VALUES (18, 'Istarska', 'XVIII');
INSERT INTO `counties` (`id`, `name`, `number`) VALUES (20, 'Međimurska', 'XX');
INSERT INTO `counties` (`id`, `name`, `number`) VALUES (21, 'Grad Zagreb', 'XXI');
COMMIT;