START TRANSACTION;
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Bedenica', 1, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Bistra', 1, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Brckovljani', 1, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Brdovec', 1, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Dubrava', 1, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Dubravica', 1, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Dugo Selo', 1, 'CITY_OR_TOWN');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Farkaševac', 1, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Gradec', 1, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Ivanić-Grad', 1, 'CITY_OR_TOWN');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Jakovlje', 1, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Jastrebarsko', 1, 'CITY_OR_TOWN');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Klinča Sela', 1, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Kloštar Ivanić', 1, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Krašić', 1, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Kravarsko', 1, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Križ', 1, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Luka', 1, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Marija Gorica', 1, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Orle', 1, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Pisarovina', 1, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Pokupsko', 1, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Preseka', 1, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Pušća', 1, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Rakovec', 1, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Rugvica', 1, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Samobor', 1, 'CITY_OR_TOWN');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Stupnik', 1, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Sveta Nedelja', 1, 'CITY_OR_TOWN');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Sveti Ivan Zelina', 1, 'CITY_OR_TOWN');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Velika Gorica', 1, 'CITY_OR_TOWN');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Vrbovec', 1, 'CITY_OR_TOWN');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Zaprešić', 1, 'CITY_OR_TOWN');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Žumberak', 1, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Bedekovčina', 2, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Budinščina', 2, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Desinić', 2, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Donja Stubica', 2, 'CITY_OR_TOWN');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Đurmanec', 2, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Gornja Stubica', 2, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Hrašćina', 2, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Hum na Sutli', 2, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Jesenje', 2, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Klanjec', 2, 'CITY_OR_TOWN');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Konjščina', 2, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Kraljevec na Sutli', 2, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Krapina', 2, 'CITY_OR_TOWN');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Krapinske Toplice', 2, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Kumrovec', 2, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Lobor', 2, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Mače', 2, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Marija Bistrica', 2, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Mihovljan', 2, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Novi Golubovec', 2, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Oroslavje', 2, 'CITY_OR_TOWN');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Petrovsko', 2, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Pregrada', 2, 'CITY_OR_TOWN');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Radoboj', 2, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Stubičke Toplice', 2, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Sveti Križ Začretje', 2, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Tuhelj', 2, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Veliko Trgovišće', 2, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Zabok', 2, 'CITY_OR_TOWN');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Zagorska Sela', 2, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Zlatar', 2, 'CITY_OR_TOWN');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Zlatar Bistrica', 2, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Donji Kukuruzari', 3, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Dvor', 3, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Glina', 3, 'CITY_OR_TOWN');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Gvozd', 3, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Hrvatska Dubica', 3, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Hrvatska Kostajnica', 3, 'CITY_OR_TOWN');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Jasenovac', 3, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Kutina', 3, 'CITY_OR_TOWN');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Lekenik', 3, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Lipovljani', 3, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Majur', 3, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Martinska Ves', 3, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Novska', 3, 'CITY_OR_TOWN');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Petrinja', 3, 'CITY_OR_TOWN');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Popovača', 3, 'CITY_OR_TOWN');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Sisak', 3, 'CITY_OR_TOWN');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Sunja', 3, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Topusko', 3, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Velika Ludina', 3, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Barilović', 4, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Bosiljevo', 4, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Cetingrad', 4, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Draganić', 4, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Generalski Stol', 4, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Josipdol', 4, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Kamanje', 4, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Krnjak', 4, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Lasinja', 4, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Netretić', 4, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Plaški', 4, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Rakovica', 4, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Ribnik', 4, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Saborsko', 4, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Tounj', 4, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Vojnić', 4, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Žakanje', 4, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Duga Resa', 4, 'CITY_OR_TOWN');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Karlovac', 4, 'CITY_OR_TOWN');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Ogulin', 4, 'CITY_OR_TOWN');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Ozalj', 4, 'CITY_OR_TOWN');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Slunj', 4, 'CITY_OR_TOWN');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Brinje', 9, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Donji Lapac', 9, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Gospić', 9, 'CITY_OR_TOWN');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Karlobag', 9, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Lovinac', 9, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Novalja', 9, 'CITY_OR_TOWN');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Otočac', 9, 'CITY_OR_TOWN');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Perušić', 9, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Plitvička Jezera', 9, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Senj', 9, 'CITY_OR_TOWN');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Udbina', 9, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Vrhovine', 9, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Bednja', 5, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Beretinec', 5, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Breznica', 5, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Breznički Hum', 5, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Cestica', 5, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Donja Voća', 5, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Gornji Kneginec', 5, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Jalžabet', 5, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Ivanec', 5, 'CITY_OR_TOWN');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Klenovnik', 5, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Ljubešćica', 5, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Lepoglava', 5, 'CITY_OR_TOWN');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Ludbreg', 5, 'CITY_OR_TOWN');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Mali Bukovec', 5, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Martijanec', 5, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Maruševec', 5, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Novi Marof', 5, 'CITY_OR_TOWN');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Petrijanec', 5, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Sračinec', 5, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Sveti Đurđ', 5, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Sveti Ilija', 5, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Trnovec Bartolovečki', 5, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Varaždin', 5, 'CITY_OR_TOWN');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Varaždinske Toplice', 5, 'CITY_OR_TOWN');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Veliki Bukovec', 5, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Vidovec', 5, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Vinica', 5, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Visoko', 5, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Drnje', 6, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Đelekovec', 6, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Đurđevac', 6, 'CITY_OR_TOWN');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Ferdinandovac', 6, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Gola', 6, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Gornja Rijeka', 6, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Hlebine', 6, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Kalinovac', 6, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Kalnik', 6, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Kloštar Podravski', 6, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Koprivnički Bregi', 6, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Koprivnica', 6, 'CITY_OR_TOWN');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Koprivnički Ivanec', 6, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Legrad', 6, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Molve', 6, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Novigrad Podravski', 6, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Novo Virje', 6, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Peteranec', 6, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Podravske Sesvete', 6, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Rasinja', 6, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Sokolovac', 6, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Sveti Ivan Žabno', 6, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Sveti Petar Orehovec', 6, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Virje', 6, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Križevci', 6, 'CITY_OR_TOWN');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Berek', 7, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Bjelovar', 7, 'CITY_OR_TOWN');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Čazma', 7, 'CITY_OR_TOWN');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Daruvar', 7, 'CITY_OR_TOWN');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Dežanovac', 7, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Đulovac', 7, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Garešnica', 7, 'CITY_OR_TOWN');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Grubišno Polje', 7, 'CITY_OR_TOWN');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Hercegovac', 7, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Ivanska', 7, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Kapela', 7, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Končanica', 7, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Nova Rača', 7, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Rovišće', 7, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Severin', 7, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Sirač', 7, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Šandrovac', 7, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Štefanje', 7, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Velika Pisanica', 7, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Velika Trnovitica', 7, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Veliki Grđevac', 7, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Veliko Trojstvo', 7, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Zrinski Topolovac', 7, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Bakar', 8, 'CITY_OR_TOWN');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Baška', 8, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Brod Moravice', 8, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Cres', 8, 'CITY_OR_TOWN');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Crikvenica', 8, 'CITY_OR_TOWN');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Čabar', 8, 'CITY_OR_TOWN');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Čavle', 8, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Delnice', 8, 'CITY_OR_TOWN');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Dobrinj', 8, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Fužine', 8, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Jelenje', 8, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Kastav', 8, 'CITY_OR_TOWN');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Klana', 8, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Kostrena', 8, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Kraljevica', 8, 'CITY_OR_TOWN');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Krk', 8, 'CITY_OR_TOWN');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Lokve', 8, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Lopar', 8, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Lovran', 8, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Mali Lošinj', 8, 'CITY_OR_TOWN');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Malinska-Dubašnica', 8, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Matulji', 8, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Mošćenička Draga', 8, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Mrkopalj', 8, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Novi Vinodolski', 8, 'CITY_OR_TOWN');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Omišalj', 8, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Opatija', 8, 'CITY_OR_TOWN');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Punat', 8, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Rab', 8, 'CITY_OR_TOWN');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Ravna Gora', 8, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Rijeka', 8, 'CITY_OR_TOWN');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Skrad', 8, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Vinodolska općina', 8, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Viškovo', 8, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Vrbnik', 8, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Vrbovsko', 8, 'CITY_OR_TOWN');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Crnac', 10, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Čačinci', 10, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Čađavica', 10, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Gradina', 10, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Lukač', 10, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Mikleuš', 10, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Nova Bukovica', 10, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Orahovica', 10, 'CITY_OR_TOWN');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Pitomača', 10, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Slatina', 10, 'CITY_OR_TOWN');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Sopje', 10, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Suhopolje', 10, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Špišić Bukovica', 10, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Virovitica', 10, 'CITY_OR_TOWN');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Voćin', 10, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Zdenci', 10, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Brestovac', 11, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Čaglin', 11, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Jakšić', 11, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Kaptol', 11, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Kutjevo', 11, 'CITY_OR_TOWN');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Lipik', 11, 'CITY_OR_TOWN');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Pakrac', 11, 'CITY_OR_TOWN');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Pleternica', 11, 'CITY_OR_TOWN');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Požega', 11, 'CITY_OR_TOWN');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Velika', 11, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Bebrina', 12, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Brodski Stupnik', 12, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Bukovlje', 12, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Cernik', 12, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Davor', 12, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Donji Andrijevci', 12, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Dragalić', 12, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Garčin', 12, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Gornja Vrba', 12, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Gornji Bogićevci', 12, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Gundinci', 12, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Klakar', 12, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Nova Gradiška', 12, 'CITY_OR_TOWN');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Nova Kapela', 12, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Okučani', 12, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Oprisavci', 12, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Oriovac', 12, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Podcrkavlje', 12, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Rešetari', 12, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Sibinj', 12, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Sikirevci', 12, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Slavonski Brod', 12, 'CITY_OR_TOWN');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Slavonski Šamac', 12, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Stara Gradiška', 12, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Staro Petrovo Selo', 12, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Velika Kopanica', 12, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Vrbje', 12, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Vrpolje', 12, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Benkovac', 13, 'CITY_OR_TOWN');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Bibinje', 13, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Biograd na Moru', 13, 'CITY_OR_TOWN');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Galovac', 13, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Gračac', 13, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Jasenice', 13, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Kali', 13, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Kolan', 13, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Kukljica', 13, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Lišane Ostrovičke', 13, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Nin', 13, 'CITY_OR_TOWN');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Novigrad', 13, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Obrovac', 13, 'CITY_OR_TOWN');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Pag', 13, 'CITY_OR_TOWN');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Pakoštane', 13, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Pašman', 13, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Polača', 13, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Poličnik', 13, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Posedarje', 13, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Povljana', 13, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Preko', 13, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Privlaka', 13, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Ražanac', 13, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Sali', 13, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Stankovci', 13, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Starigrad', 13, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Sukošan', 13, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Sveti Filip i Jakov', 13, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Škabrnja', 13, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Tkon', 13, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Vir', 13, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Vrsi', 13, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Zadar', 13, 'CITY_OR_TOWN');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Zemunik Donji', 13, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Antunovac', 14, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Beli Manastir', 14, 'CITY_OR_TOWN');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Belišće', 14, 'CITY_OR_TOWN');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Bilje', 14, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Bizovac', 14, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Čeminac', 14, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Čepin', 14, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Darda', 14, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Donja Motičina', 14, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Donji Miholjac', 14, 'CITY_OR_TOWN');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Draž', 14, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Drenje', 14, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Đakovo', 14, 'CITY_OR_TOWN');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Đurđenovac', 14, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Erdut', 14, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Ernestinovo', 14, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Feričanci', 14, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Gorjani', 14, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Jagodnjak', 14, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Kneževi Vinogradi', 14, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Koška', 14, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Levanjska Varoš', 14, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Magadenovac', 14, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Marijanci', 14, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Našice', 14, 'CITY_OR_TOWN');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Osijek', 14, 'CITY_OR_TOWN');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Petlovac', 14, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Petrijevci', 14, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Podgorač', 14, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Podravska Moslavina', 14, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Popovac', 14, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Punitovci', 14, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Satnica Đakovačka', 14, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Semeljci', 14, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Strizivojna', 14, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Šodolovci', 14, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Trnava', 14, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Valpovo', 14, 'CITY_OR_TOWN');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Viljevo', 14, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Viškovci', 14, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Vladislavci', 14, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Vuka', 14, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Blato', 19, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Dubrovačko primorje', 19, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Dubrovnik', 19, 'CITY_OR_TOWN');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Janjina', 19, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Konavle', 19, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Korčula', 19, 'CITY_OR_TOWN');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Kula Norinska', 19, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Lastovo', 19, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Lumbarda', 19, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Metković', 19, 'CITY_OR_TOWN');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Mljet', 19, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Opuzen', 19, 'CITY_OR_TOWN');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Orebić', 19, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Ploče', 19, 'CITY_OR_TOWN');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Pojezerje', 19, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Slivno', 19, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Smokvica', 19, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Ston', 19, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Trpanj', 19, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Vela Luka', 19, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Zažablje', 19, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Župa dubrovačka', 19, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Bilice', 15, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Biskupija', 15, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Civljane', 15, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Drniš', 15, 'CITY_OR_TOWN');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Ervenik', 15, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Kijevo', 15, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Kistanje', 15, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Knin', 15, 'CITY_OR_TOWN');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Murter-Kornati', 15, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Pirovac', 15, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Primošten', 15, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Promina', 15, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Rogoznica', 15, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Ružić', 15, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Skradin', 15, 'CITY_OR_TOWN');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Šibenik', 15, 'CITY_OR_TOWN');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Tisno', 15, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Tribunj', 15, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Unešić', 15, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Vodice', 15, 'CITY_OR_TOWN');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Andrijaševci', 16, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Babina Greda', 16, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Bogdanovci', 16, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Borovo', 16, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Bošnjaci', 16, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Cerna', 16, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Drenovci', 16, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Gradište', 16, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Gunja', 16, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Ilok', 16, 'CITY_OR_TOWN');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Ivankovo', 16, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Jarmina', 16, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Lovas', 16, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Markušica', 16, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Negoslavci', 16, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Nijemci', 16, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Nuštar', 16, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Otok', 16, 'CITY_OR_TOWN');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Privlaka', 16, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Stari Jankovci', 16, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Stari Mikanovci', 16, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Štitar', 16, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Tompojevci', 16, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Tordinci', 16, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Tovarnik', 16, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Trpinja', 16, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Vinkovci', 16, 'CITY_OR_TOWN');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Vođinci', 16, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Vrbanja', 16, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Vukovar', 16, 'CITY_OR_TOWN');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Županja', 16, 'CITY_OR_TOWN');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Baška Voda', 17, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Bol', 17, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Brela', 17, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Cista Provo', 17, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Dicmo', 17, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Dugi Rat', 17, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Dugopolje', 17, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Gradac', 17, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Hrvace', 17, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Hvar', 17, 'CITY_OR_TOWN');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Imotski', 17, 'CITY_OR_TOWN');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Jelsa', 17, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Kaštela', 17, 'CITY_OR_TOWN');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Klis', 17, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Komiža', 17, 'CITY_OR_TOWN');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Lećevica', 17, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Lokvičići', 17, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Lovreć', 17, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Makarska', 17, 'CITY_OR_TOWN');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Marina', 17, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Milna', 17, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Muć', 17, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Nerežišća', 17, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Okrug', 17, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Omiš', 17, 'CITY_OR_TOWN');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Otok', 17, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Podbablje', 17, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Podgora', 17, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Podstrana', 17, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Postira', 17, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Prgomet', 17, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Primorski Dolac', 17, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Proložac', 17, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Pučišća', 17, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Runovići', 17, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Seget', 17, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Selca', 17, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Sinj', 17, 'CITY_OR_TOWN');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Solin', 17, 'CITY_OR_TOWN');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Split', 17, 'CITY_OR_TOWN');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Stari Grad', 17, 'CITY_OR_TOWN');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Sućuraj', 17, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Supetar', 17, 'CITY_OR_TOWN');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Sutivan', 17, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Šestanovac', 17, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Šolta', 17, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Trilj', 17, 'CITY_OR_TOWN');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Trogir', 17, 'CITY_OR_TOWN');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Tučepi', 17, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Vis', 17, 'CITY_OR_TOWN');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Vrgorac', 17, 'CITY_OR_TOWN');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Vrlika', 17, 'CITY_OR_TOWN');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Zadvarje', 17, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Zagvozd', 17, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Zmijavci', 17, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Bale-Valle', 18, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Barban', 18, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Brtonigla-Verteneglio', 18, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Buje-Buie', 18, 'CITY_OR_TOWN');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Buzet', 18, 'CITY_OR_TOWN');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Cerovlje', 18, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Fažana-Fasana', 18, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Funtana-Fontane', 18, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Gračišće', 18, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Grožnjan-Grisignana', 18, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Kanfanar', 18, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Karojba', 18, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Kaštelir-Labinci-Castelliere-S. Domenica', 18, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Kršan', 18, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Labin', 18, 'CITY_OR_TOWN');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Lanišće', 18, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Ližnjan-Lisignano', 18, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Lupoglav', 18, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Marčana', 18, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Medulin', 18, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Motovun-Montona', 18, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Novigrad-Cittanova', 18, 'CITY_OR_TOWN');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Oprtalj-Portole', 18, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Pazin', 18, 'CITY_OR_TOWN');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Pićan', 18, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Poreč-Parenzo', 18, 'CITY_OR_TOWN');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Pula-Pola', 18, 'CITY_OR_TOWN');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Raša', 18, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Rovinj-Rovigno', 18, 'CITY_OR_TOWN');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Sveta Nedelja', 18, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Sveti Lovreč', 18, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Sveti Petar u Šumi', 18, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Svetvinčenat', 18, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Tar-Vabriga-Torre Abrega', 18, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Tinjan', 18, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Umag-Umago', 18, 'CITY_OR_TOWN');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Višnjan-Visignano', 18, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Vižinada-Visinada', 18, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Vodnjan-Dignano', 18, 'CITY_OR_TOWN');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Vrsar-Orsera', 18, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Žminj', 18, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Belica', 20, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Čakovec', 20, 'CITY_OR_TOWN');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Dekanovec', 20, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Domašinec', 20, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Donja Dubrava', 20, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Donji Kraljevec', 20, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Donji Vidovec', 20, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Goričan', 20, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Gornji Mihaljevec', 20, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Kotoriba', 20, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Mala Subotica', 20, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Mursko Središće', 20, 'CITY_OR_TOWN');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Nedelišće', 20, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Orehovica', 20, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Podturen', 20, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Prelog', 20, 'CITY_OR_TOWN');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Pribislavec', 20, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Selnica', 20, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Strahoninec', 20, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Sveta Marija', 20, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Sveti Juraj na Bregu', 20, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Sveti Martin na Muri', 20, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Šenkovec', 20, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Štrigova', 20, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Vratišinec', 20, 'MUNICIPALITY');
INSERT INTO `municipalities` (`name`, `county_id`, `type`) VALUES ('Zagreb', 21, 'CITY_OR_TOWN');
COMMIT;